name: SonarQube SAST Workflow with TestContainers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube-scan:
    name: Run SonarQube Analysis with TestContainers
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      security-events: write 
      actions: read
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'adopt'
          cache: gradle

      - name: Make Gradle Wrapper Executable
        run: chmod +x Demo/gradlew

      - name: Start SonarQube Container
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:community
          echo "Waiting for SonarQube to start..."
          timeout 900 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:9000/api/system/status)" != "200" ]]; do sleep 5; done' || false
          docker logs sonarqube
          echo "SonarQube is ready"

      - name: Create Project Key
        run: |
          curl -X POST -u admin:new_password \
            "http://localhost:9000/api/projects/create?project=Demo&name=Demo"

      - name: Build and Test
        run: |
          cd Demo && ./gradlew clean build test --info  

      - name: Run Sonar Analysis with Gradle
        run: ./gradlew sonar -Dsonar.host.url=http://localhost:9000 \
                             -Dsonar.login=admin \
                             -Dsonar.password=admin123 \
                             -Dsonar.projectKey=Demo

      - name: Generate SARIF Report
        run: |
          curl -u admin:new_password \
            "http://localhost:9000/api/issues/search?componentKeys=Demo&resolved=false" \
            -o issues.json

      - name: Upload SARIF Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonar-issues
          path: issues.json
      

      